pub mod materials;
pub mod lattice;
pub mod moire;
pub mod density;
pub mod fft;
pub mod colormap;
pub mod isotopes;
pub mod isotope_effects;
pub mod magnetic;
pub mod topological;
pub mod graphene;
pub mod curvature;
pub mod bm_model;

pub use materials::{LatticeType, Material};
pub use lattice::Lattice2D;
pub use moire::{MoireConfig, MoireResult};
pub use density::{DensityConfig, DensityResult};
pub use fft::{FftPeak, fft_frequencies, identify_peaks};
pub use isotopes::IsotopeConfig;
pub use isotope_effects::{IsotopeEffects, IsotopeEffectsConfig};
pub use magnetic::{MagneticFieldConfig, VortexLatticeResult, ZeemanResult};
pub use topological::{ProximityConfig, ProximityResult, CooperSurface3D};
pub use graphene::{GrapheneStackConfig, GrapheneStackConfigV2, GrapheneStackResult, FlatBandConfig, FlatBandResult, StackingKind, SupermoireConfig, SupermoireResult};
pub use curvature::{CurvatureConfig, CurvatureResult, CurvatureGeometry};
pub use bm_model::{BMConfig, BandStructure, DosResult, compute_band_structure, compute_dos, flat_band_width_mev};
