"""Cross-stack colormap LUT and 3D scene presets.

The JSON file at :file:`colormaps_data.json` is generated by
``cargo run -p moire-core --bin dump_lut`` from
``crates/moire-core/src/colormap.rs``. Both stacks must sample the same
palette so screenshots from the Python Plotly app and the Rust desktop app
look identical.

Public API
----------
- :func:`get_plotly_colorscale` — named colormap -> 256-stop Plotly colorscale.
- :data:`LIGHTING_PRESET` / :data:`LIGHT_POSITION` — single preset applied to
  every 3D surface so lighting stays consistent across pages.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Final

_DATA_PATH: Final[Path] = Path(__file__).with_name("colormaps_data.json")


@lru_cache(maxsize=1)
def _load_tables() -> dict[str, list[list[int]]]:
    raw = json.loads(_DATA_PATH.read_text())
    return {k: v for k, v in raw.items() if not k.startswith("_")}


def available_colormaps() -> list[str]:
    return sorted(_load_tables().keys())


@lru_cache(maxsize=16)
def get_plotly_colorscale(name: str) -> list[list[object]]:
    """Return a 256-stop Plotly colorscale for ``name`` ('viridis', ...).

    Output format is the list-of-pairs form that Plotly accepts anywhere a
    colorscale is expected: ``[[t, "rgb(R,G,B)"], ...]`` with ``t`` in
    ``[0, 1]``.
    """
    tables = _load_tables()
    key = name.lower().replace("_r", "_r")  # passthrough; reverse handled below
    reverse = key.endswith("_r")
    base = key[:-2] if reverse else key
    if base not in tables:
        raise KeyError(
            f"unknown colormap {name!r}; available: {available_colormaps()}"
        )
    rows = tables[base]
    n = len(rows)
    if reverse:
        rows = list(reversed(rows))
    # Build stops at [i/(n-1)] with an rgb string; Plotly accepts either rgb()
    # strings or hex — rgb() keeps the JSON authoritative.
    return [
        [i / (n - 1), f"rgb({r}, {g}, {b})"]
        for i, (r, g, b) in enumerate(rows)
    ]


# ---------------------------------------------------------------------------
# 3D scene presets — single source of truth consumed by figure_factory helpers.
# ---------------------------------------------------------------------------

# Lighting tuned to make the moire ridges and Cooper-pair isosurface readable
# without over-specular highlights. Applied via ``go.Surface(lighting=...)``.
LIGHTING_PRESET: Final[dict[str, float]] = dict(
    ambient=0.4,
    diffuse=0.8,
    specular=0.3,
    roughness=0.5,
    fresnel=0.2,
)

# Light position is in scene-data units, not normalised — Plotly's convention.
LIGHT_POSITION: Final[dict[str, int]] = dict(x=100, y=200, z=0)

# Named iso-style camera used for consistent screenshots; moved here from
# figure_factory._scene_camera_presets() so the script capture path and the
# Dash pages share one definition.
CAMERA_PRESETS: Final[dict[str, dict]] = {
    "iso":  dict(eye=dict(x=1.5, y=1.5, z=1.0)),
    "top":  dict(eye=dict(x=0.0, y=0.0, z=2.5), up=dict(x=0, y=1, z=0)),
    "side": dict(eye=dict(x=2.5, y=0.0, z=0.2)),
}


__all__ = [
    "CAMERA_PRESETS",
    "LIGHTING_PRESET",
    "LIGHT_POSITION",
    "available_colormaps",
    "get_plotly_colorscale",
]
